"""empty message

Revision ID: 2c4144d75645
Revises: 
Create Date: 2018-04-06 00:13:34.562405

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2c4144d75645'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('family_name', sa.TEXT(), nullable=False),
    sa.Column('given_name', sa.TEXT(), nullable=False),
    sa.Column('gender', sa.TEXT(), nullable=True),
    sa.Column('dob', sa.DATE(), nullable=False),
    sa.Column('email', sa.TEXT(), nullable=False),
    sa.Column('source_type', sa.TEXT(), nullable=False),
    sa.Column('avartar', postgresql.BYTEA(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('avartar'),
    sa.UniqueConstraint('created_at'),
    sa.UniqueConstraint('dob'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('source_type')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
